# -*- coding: utf-8 -*-
"""AIWEEK3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QR3s2zAuy5VF8hfjy0271jkAY0MIfBs2
"""

import heapq

initial_state = (
    (2, 8, 3),
    (1, 6, 4),
    (0, 7, 5)
)

goal_state = (
    (1, 2, 3),
    (8, 0, 4),
    (7, 6, 5)
)

# Heuristic: Number of tiles out of place
def heuristic(state):
    count = 0
    for i in range(3):
        for j in range(3):
            if state[i][j] != 0 and state[i][j] != goal_state[i][j]:
                count += 1
    return count

# Find possible next states
def get_neighbors(state):
    neighbors = []
    for i in range(3):
        for j in range(3):
            if state[i][j] == 0:
                x, y = i, j
                break
        else:
            continue
        break

    moves = [(1, 0), (-1, 0), (0, 1), (0, -1)]

    for dx, dy in moves:
        nx, ny = x + dx, y + dy

        if 0 <= nx < 3 and 0 <= ny < 3:
            new_state = [list(row) for row in state]
            new_state[x][y], new_state[nx][ny] = (
                new_state[nx][ny],
                new_state[x][y]
            )

            neighbors.append(tuple(tuple(row) for row in new_state))

    return neighbors

# A* algorithm
def astar(start):
    # Priority queue: (f(n), g(n), state, path)
    pq = [(heuristic(start), 0, start, [start])]
    visited = set()
    cost = {start: 0}

    while pq:
        f, g, state, path = heapq.heappop(pq)

        if state == goal_state:
            return path

        if state in visited:
            continue
        visited.add(state)

        for neighbor in get_neighbors(state):
            new_g = g + 1

            if neighbor not in cost or new_g < cost[neighbor]:
                cost[neighbor] = new_g
                new_f = new_g + heuristic(neighbor)

                heapq.heappush(
                    pq,
                    (new_f, new_g, neighbor, path + [neighbor])
                )

    return None

# Print solution
solution = astar(initial_state)

if solution:
    print("Solution found!")
    print("Number of moves:", len(solution) - 1)

    for step, state in enumerate(solution):
        print("\nStep", step)
        for row in state:
            print(row)
        print("Heuristic h(n):", heuristic(state))
else:
    print("No solution exists.")

print("Dharshan Srinivas S")
print("1WA24CS109")