# -*- coding: utf-8 -*-
"""AIWEEK2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B6DucREQPxYVh5oluvWYjSPlzVCwGiqo
"""

from copy import deepcopy

GOAL = (1, 2, 3, 4, 5, 6, 7, 8, 0)

def print_board(state):
    for i in range(0, 9, 3):
        print(*state[i:i + 3])
    print()

def get_neighbors(state):
    zero = state.index(0)
    row, col = divmod(zero, 3)
    neighbors = []

    moves = [
        (-1, 0),  # Up
        (1, 0),   # Down
        (0, -1),  # Left
        (0, 1)    # Right
    ]

    for dr, dc in moves:
        nr, nc = row + dr, col + dc

        if 0 <= nr < 3 and 0 <= nc < 3:
            new_zero = nr * 3 + nc
            new_state = list(state)

            new_state[zero], new_state[new_zero] = (
                new_state[new_zero], new_state[zero]
            )

            neighbors.append(tuple(new_state))

    return neighbors

def dfs(start, limit):
    path = [start]
    visited = set()

    def search(state, depth):
        if state == GOAL:
            return True

        if depth == limit:
            return False

        visited.add(state)

        for neighbor in get_neighbors(state):
            if neighbor not in visited:
                path.append(neighbor)

                if search(neighbor, depth + 1):
                    return True

                path.pop()

        return False

    if search(start, 0):
        return path
    return None

def ids(start, max_depth):
    for limit in range(max_depth + 1):
        result = dfs(start, limit)

        if result:
            print("Solution found at depth:", limit)
            return result

    return None

# Main program
print("Enter the initial state (use 0 for blank):")
start = tuple(map(int, input().split()))

if len(start) != 9 or set(start) != set(range(9)):
    print("Invalid input! Enter numbers 0 to 8 exactly once.")
else:
    print("\n1. DFS")
    print("2. Iterative Deepening Search (IDS)")
    choice = input("Enter choice: ")

    depth = int(input("Enter maximum depth: "))

    if choice == "1":
        solution = dfs(start, depth)
    elif choice == "2":
        solution = ids(start, depth)
    else:
        solution = None
        print("Invalid choice!")

    if solution:
        print("\nSolution path:")
        for step, state in enumerate(solution):
            print("Step", step)
            print_board(state)
        print("Total moves:", len(solution) - 1)
    elif choice in ("1", "2"):
        print("No solution found within the depth limit.")
print("Dharshan Srinivas S")
print("1WA24CS109")